
define class Din_Datosdeentidades as Custom

	*-----------------------------------------------------------------------------------------
	function ObtenerIdentificadorDeEntidad( tcEntidad as string ) as string
		local lcRetorno as string, lcEntidad as string
		lcRetorno = ''
		lcEntidad = upper( alltrim( tcEntidad ) )
		do case
			case lcEntidad == 'ARTICULO'
				lcRetorno = '001'
			case lcEntidad == 'PROVEEDOR'
				lcRetorno = '002'
			case lcEntidad == 'MATERIAL'
				lcRetorno = '003'
			case lcEntidad == 'COLOR'
				lcRetorno = '004'
			case lcEntidad == 'LISTADEPRECIOS'
				lcRetorno = '005'
			case lcEntidad == 'VALOR'
				lcRetorno = '006'
			case lcEntidad == 'VENDEDOR'
				lcRetorno = '007'
			case lcEntidad == 'CLIENTE'
				lcRetorno = '008'
			case lcEntidad == 'FACTURA'
				lcRetorno = '011'
			case lcEntidad == 'STOCKCOMBINACION'
				lcRetorno = '012'
			case lcEntidad == 'PROVINCIA'
				lcRetorno = '013'
			case lcEntidad == 'CORREDOR'
				lcRetorno = '014'
			case lcEntidad == 'BANCO'
				lcRetorno = '015'
			case lcEntidad == 'SUCURSAL'
				lcRetorno = '016'
			case lcEntidad == 'DOCUMENTOPROPIO'
				lcRetorno = '017'
			case lcEntidad == 'PRECIODEARTICULO'
				lcRetorno = '018'
			case lcEntidad == 'TICKETFACTURA'
				lcRetorno = '019'
			case lcEntidad == 'NOTADECREDITO'
				lcRetorno = '020'
			case lcEntidad == 'NOTADEDEBITO'
				lcRetorno = '021'
			case lcEntidad == 'TICKETNOTADECREDITO'
				lcRetorno = '022'
			case lcEntidad == 'TICKETNOTADEDEBITO'
				lcRetorno = '023'
			case lcEntidad == 'STOCKARTICULOS'
				lcRetorno = '024'
			case lcEntidad == 'MONEDA'
				lcRetorno = '025'
			case lcEntidad == 'ORIGENDEDATOS'
				lcRetorno = '027'
			case lcEntidad == 'ENTIDADFINANCIERA'
				lcRetorno = '028'
			case lcEntidad == 'MOTIVO'
				lcRetorno = '030'
			case lcEntidad == 'REMITO'
				lcRetorno = '032'
			case lcEntidad == 'CAJAAUDITORIA'
				lcRetorno = '033'
			case lcEntidad == 'CAJAESTADO'
				lcRetorno = '034'
			case lcEntidad == 'CAJASALDOS'
				lcRetorno = '035'
			case lcEntidad == 'MOVIMIENTODECAJA'
				lcRetorno = '036'
			case lcEntidad == 'CONCEPTOCAJA'
				lcRetorno = '037'
			case lcEntidad == 'COMPROBANTEDECAJA'
				lcRetorno = '038'
			case lcEntidad == 'GRUPOVALOR'
				lcRetorno = '039'
			case lcEntidad == 'MODIFICACIONPRECIOS'
				lcRetorno = '040'
			case lcEntidad == 'MOVIMIENTODESTOCK'
				lcRetorno = '043'
			case lcEntidad == 'BUZON'
				lcRetorno = '044'
			case lcEntidad == 'PAISES'
				lcRetorno = '045'
			case lcEntidad == 'TALONARIO'
				lcRetorno = '046'
			case lcEntidad == 'NUMERACIONES'
				lcRetorno = '047'
			case lcEntidad == 'DEVOLUCION'
				lcRetorno = '048'
			case lcEntidad == 'INFORMACIONADICIONALCOMPVTAS'
				lcRetorno = '049'
			case lcEntidad == 'PERCEPCION'
				lcRetorno = '050'
			case lcEntidad == 'AJUSTEDESTOCK'
				lcRetorno = '051'
			case lcEntidad == 'AGRUPAMIENTO'
				lcRetorno = 'AGR'
			case lcEntidad == 'BASEDEDATOS'
				lcRetorno = '052'
			case lcEntidad == 'CTACTE'
				lcRetorno = '053'
			case lcEntidad == 'RECIBO'
				lcRetorno = '054'
			case lcEntidad == 'MEMORIA'
				lcRetorno = 'MEM'
			case lcEntidad == 'DISENOIMPRESION'
				lcRetorno = 'IMP'
			case lcEntidad == 'TIPOAREAIMPRESION'
				lcRetorno = 'ARE'
			case lcEntidad == 'ESTILOIMPRESION'
				lcRetorno = 'ESI'
			case lcEntidad == 'TIPOATRIBUTOIMPRESION'
				lcRetorno = 'ATR'
			case lcEntidad == 'SELECCIONDISENOIMPRESION'
				lcRetorno = 'SDI'
			case lcEntidad == 'DISENOEXPO'
				lcRetorno = 'EXP'
			case lcEntidad == 'DESCUENTO'
				lcRetorno = 'DES'
			case lcEntidad == 'FORMATOEXPORTACION'
				lcRetorno = 'FOE'
			case lcEntidad == 'TIPOAREAEXPORTACION'
				lcRetorno = 'TAE'
			case lcEntidad == 'TIPOATRIBUTOSEXPORTACION'
				lcRetorno = 'TBE'
			case lcEntidad == 'TIPOARCHIVOEXPORTACION'
				lcRetorno = 'THE'
			case lcEntidad == 'TIPOREGISTROEXPORTACION'
				lcRetorno = 'TRE'
			case lcEntidad == 'CONVERSION'
				lcRetorno = 'CDE'
			case lcEntidad == 'CONVERSIONVALORES'
				lcRetorno = 'VCE'
			case lcEntidad == 'EXPOAGRUPADAS'
				lcRetorno = 'EXA'
			case lcEntidad == 'TIPOARCHIVOIMPORTACION'
				lcRetorno = 'THI'
			case lcEntidad == 'IMPOAGRUPADAS'
				lcRetorno = 'IMA'
			case lcEntidad == 'TIINVENTARIOACONT'
				lcRetorno = 'TIT'
			case lcEntidad == 'TIINVENTARIOACONTDETALLE'
				lcRetorno = 'ITD'
			case lcEntidad == 'TIINVENTARIOFISICO'
				lcRetorno = 'TIF'
			case lcEntidad == 'TIINVENTARIOFISICODETALLE'
				lcRetorno = 'FIT'
			case lcEntidad == 'TIDIFERENCIASDEINVENTARIO'
				lcRetorno = 'TIN'
			case lcEntidad == 'TIDIFERENCIASDEINVENTARIODETALLE'
				lcRetorno = 'TID'
			case lcEntidad == 'EQUIVALENCIA'
				lcRetorno = 'CBA'
			case lcEntidad == 'REDONDEODEPRECIOS'
				lcRetorno = 'RED'
			case lcEntidad == 'CONDICIONIMPO'
				lcRetorno = 'CON'
			case lcEntidad == 'DISENOIMPO'
				lcRetorno = 'DIM'
			case lcEntidad == 'PICKING'
				lcRetorno = 'PIK'
			case lcEntidad == 'DATOSFISCALES'
				lcRetorno = 'DFI'
			case lcEntidad == 'JURISDICCION'
				lcRetorno = 'JUR'
			case lcEntidad == 'CAI'
				lcRetorno = 'CAI'
			case lcEntidad == 'SCRIPT'
				lcRetorno = 'SCR'
			case lcEntidad == 'VALEDECAMBIO'
				lcRetorno = 'VCB'
			case lcEntidad == 'CONSUMOCLIENTE'
				lcRetorno = 'CCL'
			case lcEntidad == 'LIMITECONSUMO'
				lcRetorno = 'LCN'
			case lcEntidad == 'REGLASTRANSFERENCIAS'
				lcRetorno = 'RTR'
			case lcEntidad == 'ERRORESCFIBM4610KC4'
				lcRetorno = 'KC4'
			case lcEntidad == 'CODIGOPOSTAL'
				lcRetorno = 'CP8'
			case lcEntidad == 'ACCIONESAUTOMATICAS'
				lcRetorno = 'AA'
			case lcEntidad == 'SENIA'
				lcRetorno = 'SEN'
			case lcEntidad == 'PEDIDO'
				lcRetorno = 'PED'
			case lcEntidad == 'IMPRESIONDEETIQUETA'
				lcRetorno = 'IET'
			case lcEntidad == 'CLASIFICACIONCLIENTE'
				lcRetorno = '203'
			case lcEntidad == 'SENIAPENDIENTE'
				lcRetorno = 'SEP'
			case lcEntidad == 'CHEQUE'
				lcRetorno = 'CH'
			case lcEntidad == 'IMPUESTO'
				lcRetorno = 'IMS'
			case lcEntidad == 'FACTURADECOMPRA'
				lcRetorno = 'FDC'
			case lcEntidad == 'OPERADORADETARJETA'
				lcRetorno = '056'
			case lcEntidad == 'CIERREDELOTE'
				lcRetorno = '057'
			case lcEntidad == 'POS'
				lcRetorno = 'POS'
			case lcEntidad == 'CUPON'
				lcRetorno = 'CUP'
			case lcEntidad == 'PRESUPUESTO'
				lcRetorno = 'PRE'
			case lcEntidad == 'TIPOIMPUESTO'
				lcRetorno = 'TIM'
			case lcEntidad == 'TRANSPORTISTA'
				lcRetorno = 'TRA'
			case lcEntidad == 'DATOSTARJETA'
				lcRetorno = 'DP2'
			case lcEntidad == 'CALCULODEPRECIOS'
				lcRetorno = '041'
			case lcEntidad == 'TRATAMIENTOCOMPROBANTES'
				lcRetorno = 'TCO'
			case lcEntidad == 'FACTURAELECTRONICA'
				lcRetorno = '127'
			case lcEntidad == 'NOTADECREDITOELECTRONICA'
				lcRetorno = '128'
			case lcEntidad == 'NOTADEDEBITOELECTRONICA'
				lcRetorno = '129'
			case lcEntidad == 'CAE'
				lcRetorno = 'FAE'
			case lcEntidad == 'FAVORITOLISTADOS'
				lcRetorno = 'FVX'
			case lcEntidad == 'CAEPORLOTE'
				lcRetorno = 'OFA'
			case lcEntidad == 'COMPORTAMIENTOCODIGOSUGERIDOENTIDAD'
				lcRetorno = 'CCS'
			case lcEntidad == 'ZUDESCARGALAN'
				lcRetorno = 'LAN'
			case lcEntidad == 'INFORMACIONLISTADOS'
				lcRetorno = 'IAL'
			case lcEntidad == 'CTACTECOMPRA'
				lcRetorno = '130'
			case lcEntidad == 'ORDENDEPAGO'
				lcRetorno = 'ODP'
			case lcEntidad == 'NOTADEDEBITOCOMPRA'
				lcRetorno = 'NDC'
			case lcEntidad == 'NOTADECREDITOCOMPRA'
				lcRetorno = 'NCC'
			case lcEntidad == 'SUCURSALBANCARIA'
				lcRetorno = '131'
			case lcEntidad == 'CUENTABANCARIA'
				lcRetorno = '132'
			case lcEntidad == 'CHEQUERA'
				lcRetorno = '133'
			case lcEntidad == 'CHEQUEPROPIO'
				lcRetorno = 'CP'
			case lcEntidad == 'ESTADOCONTROLADORFISCAL'
				lcRetorno = '140'
			case lcEntidad == 'CANJEDECUPONES'
				lcRetorno = 'CDV'
			case lcEntidad == 'CUPONESPENDIENTES'
				lcRetorno = 'CPN'
			case lcEntidad == 'FACTURAELECTRONICAEXPORTACION'
				lcRetorno = 'FEE'
			case lcEntidad == 'INCOTERMS'
				lcRetorno = 'INT'
			case lcEntidad == 'UNIDADDEMEDIDA'
				lcRetorno = 'UDM'
			case lcEntidad == 'UNIDADDEMEDIDAAFIP'
				lcRetorno = 'EUM'
			case lcEntidad == 'PAISAFIP'
				lcRetorno = 'PAF'
			case lcEntidad == 'MONEDAAFIP'
				lcRetorno = 'MAF'
			case lcEntidad == 'NOTADECREDITOELECTRONICAEXPORTACION'
				lcRetorno = 'NEE'
			case lcEntidad == 'NOTADEDEBITOELECTRONICAEXPORTACION'
				lcRetorno = 'DEE'
			case lcEntidad == 'AGRUPAMIENTODEBUZONES'
				lcRetorno = 'ABZ'
			case lcEntidad == 'IMPRIMIRCOMPROBANTEPORLOTE'
				lcRetorno = 'ICL'
			case lcEntidad == 'FORMULA'
				lcRetorno = 'FOR'
			case lcEntidad == 'SALTODECAMPO'
				lcRetorno = 'SDC'
			case lcEntidad == 'COMISION'
				lcRetorno = 'COM'
			case lcEntidad == 'CLASEDETARJETA'
				lcRetorno = 'CDT'
			case lcEntidad == 'TIINVENTARIOFISICODETALLETMP'
				lcRetorno = 'FTT'
			case lcEntidad == 'MERCADERIAENTRANSITO'
				lcRetorno = 'MTR'
			case lcEntidad == 'MINIMOREPOSICION'
				lcRetorno = 'MIN'
			case lcEntidad == 'LISTADOSPERSONALIZADOS'
				lcRetorno = 'LPZ'
			case lcEntidad == 'REGISTRODEMANTENIMIENTO'
				lcRetorno = 'RAM'
			case lcEntidad == 'PROMOCION'
				lcRetorno = 'PR0'
			case lcEntidad == 'SELECCIONPARAINSERTAR'
				lcRetorno = 'SEI'
			case lcEntidad == 'PAGO'
				lcRetorno = 'PAG'
			case lcEntidad == 'AJUSTEDEESTADOS'
				lcRetorno = 'AES'
			case lcEntidad == 'COMPROBANTEDERETENCIONES'
				lcRetorno = 'CDR'
			case lcEntidad == 'CONVENIOMULTILATERAL'
				lcRetorno = 'CML'
			case lcEntidad == 'PRESUPUESTODECOMPRA'
				lcRetorno = 'PDC'
			case lcEntidad == 'PEDIDODECOMPRA'
				lcRetorno = 'PCO'
			case lcEntidad == 'SOLICITUDDECOMPRA'
				lcRetorno = 'SOC'
			case lcEntidad == 'REQUERIMIENTODECOMPRA'
				lcRetorno = 'RDC'
			case lcEntidad == 'REMITODECOMPRA'
				lcRetorno = 'RCO'
			case lcEntidad == 'CANCELACIONDECOMPRA'
				lcRetorno = 'CAC'
			case lcEntidad == 'PROPIEDADESLISTADOS'
				lcRetorno = 'PLI'
			case lcEntidad == 'AJUSTEDECUPON'
				lcRetorno = 'AJC'
			case lcEntidad == 'BOLSASYCAJAS'
				lcRetorno = 'BYC'
			case lcEntidad == 'AJUSTECCCLIENTE'
				lcRetorno = 'AJU'
			case lcEntidad == 'AJUSTECCPROVEEDOR'
				lcRetorno = 'AJP'
			case lcEntidad == 'CANCELACIONDESENIAS'
				lcRetorno = 'CDS'
			case lcEntidad == 'GTIN'
				lcRetorno = 'GTI'
			case lcEntidad == 'SITUACIONFISCAL'
				lcRetorno = 'STF'
			case lcEntidad == 'PASAJEDESTOCK'
				lcRetorno = 'PST'
			case lcEntidad == 'SELECCIONBASESARCHIVADAS'
				lcRetorno = 'SBA'
			case lcEntidad == 'PRECARGAETIART'
				lcRetorno = 'PET'
			case lcEntidad == 'NUEVOENBASEA'
				lcRetorno = 'NBA'
			case lcEntidad == 'LISTADEPRECIOSCALCULADA'
				lcRetorno = 'LPC'
			case lcEntidad == 'PADRONIIBB'
				lcRetorno = 'IIB'
			case lcEntidad == 'REGISTRODEACTIVIDAD'
				lcRetorno = 'ACT'
			case lcEntidad == 'CONCILIACIONDECAJA'
				lcRetorno = 'CCJ'
			case lcEntidad == 'POOLDECLASE'
				lcRetorno = 'POO'
			case lcEntidad == 'ACCESOAOBJETO'
				lcRetorno = 'AO'
			case lcEntidad == 'EXPRESIONLISTADOPERSONALIZADO'
				lcRetorno = 'ELP'
			case lcEntidad == 'CUPONESHUERFANOS'
				lcRetorno = 'CPH'
			case lcEntidad == 'NOMENCLADORARBA'
				lcRetorno = 'NAR'
			case lcEntidad == 'GRUPO'
				lcRetorno = 'GRP'
			case lcEntidad == 'CLASIFICACIONARTICULO'
				lcRetorno = '205'
			case lcEntidad == 'UNIDADDEMEDIDAARBA'
				lcRetorno = 'UMA'
			case lcEntidad == 'REMITOELECTRONICO'
				lcRetorno = 'REL'
			case lcEntidad == 'DESTINODESCARGACHEQUES'
				lcRetorno = 'DDC'
			case lcEntidad == 'DESCARGADECHEQUES'
				lcRetorno = 'DCT'
			case lcEntidad == 'FACTURADEEXPORTACION'
				lcRetorno = 'FMX'
			case lcEntidad == 'NOTADECREDITODEEXPORTACION'
				lcRetorno = 'NCX'
			case lcEntidad == 'NOTADEDEBITODEEXPORTACION'
				lcRetorno = 'NDX'
			case lcEntidad == 'EDICIONIMPUESTOIVACOMPRAS'
				lcRetorno = 'EIC'
			case lcEntidad == 'REGISTRODEBAJA'
				lcRetorno = 'RBL'
			case lcEntidad == 'NOMBREDEFANTASIA'
				lcRetorno = 'NFA'
			case lcEntidad == 'TIPODEDIRECCION'
				lcRetorno = 'TDD'
			case lcEntidad == 'CONTACTO'
				lcRetorno = 'CNT'
			case lcEntidad == 'TIPOCLIENTE'
				lcRetorno = 'TCL'
			case lcEntidad == 'CATEGORIACLIENTE'
				lcRetorno = 'CGC'
			case lcEntidad == 'DISCOVER'
				lcRetorno = 'DSC'
			case lcEntidad == 'CRITERIOSVALORES'
				lcRetorno = 'CAV'
			case lcEntidad == 'DESPACHODEIMPORTACION'
				lcRetorno = 'DDI'
			case lcEntidad == 'SELECCIONDESPACHO'
				lcRetorno = 'SDD'
			case lcEntidad == 'REGISTRODESALUDSERVIDORDEDATOS'
				lcRetorno = 'SQL'
			case lcEntidad == 'REGIMENIMPOSITIVO'
				lcRetorno = 'REG'
			case lcEntidad == 'CLASIFICACIONCONCEPTOPAGO'
				lcRetorno = 'CCP'
			case lcEntidad == 'CONCEPTOPAGO'
				lcRetorno = 'CPA'
			case lcEntidad == 'COMPROBANTEPAGO'
				lcRetorno = 'COP'
			case lcEntidad == 'COMPROBANTEDERETENCIONESIVA'
				lcRetorno = 'CRI'
			case lcEntidad == 'COMPROBANTEDERETENCIONESGANANCIAS'
				lcRetorno = 'CRG'
			case lcEntidad == 'COMPROBANTEDERETENCIONESSUSS'
				lcRetorno = 'CRS'
			case lcEntidad == 'CONDICIONDEPAGO'
				lcRetorno = 'CDP'
			case lcEntidad == 'TIPODEOPERACIONAFIP'
				lcRetorno = 'TOA'
			case lcEntidad == 'ASOCIACIONARTICULOSOPERACIONESAFIP'
				lcRetorno = 'AAO'
			case lcEntidad == 'FERIADO'
				lcRetorno = 'FER'
			case lcEntidad == 'REGISTRODEACTIVIDADDET'
				lcRetorno = 'ACD'
			case lcEntidad == 'DATOSADICIONALESCOMPROBANTESA'
				lcRetorno = 'DAA'
			case lcEntidad == 'MOTIVODATOSADICIONALESCOMPROBANTESA'
				lcRetorno = 'MDA'
			case lcEntidad == 'AGRUPAMIENTOPUBLICACIONES'
				lcRetorno = 'APP'
			case lcEntidad == 'CONCEPTOLIQUIDACIONTARJETA'
				lcRetorno = 'CLT'
			case lcEntidad == 'LIQUIDACIONDIARIA'
				lcRetorno = 'LDT'
			case lcEntidad == 'LIQUIDACIONMENSUAL'
				lcRetorno = 'LIQ'
			case lcEntidad == 'PLANDECUENTAS'
				lcRetorno = 'CTA'
			case lcEntidad == 'MAILPORLOTE'
				lcRetorno = 'MFA'
			case lcEntidad == 'EMAIL'
				lcRetorno = 'MIL'
			case lcEntidad == 'CUENTACORREO'
				lcRetorno = 'SMT'
			case lcEntidad == 'COMPROBANTEDERETENCIONRECIBIDO'
				lcRetorno = 'CRR'
			case lcEntidad == 'DATOSRETENCIONRECIBIDO'
				lcRetorno = 'DRR'
			case lcEntidad == 'REPORTEELECTRONICO'
				lcRetorno = 'RPE'
			case lcEntidad == 'COMPLETARDESDEVENTAS'
				lcRetorno = 'CVE'
			case lcEntidad == 'CENTRODECOSTO'
				lcRetorno = 'CCO'
			case lcEntidad == 'DISTRIBUCIONCENTRODECOSTO'
				lcRetorno = 'DCC'
			case lcEntidad == 'ASIENTO'
				lcRetorno = 'ASI'
			case lcEntidad == 'RAZONSOCIAL'
				lcRetorno = 'RAZ'
			case lcEntidad == 'EJERCICIO'
				lcRetorno = 'EJR'
			case lcEntidad == 'ASIGNARZBD'
				lcRetorno = 'ARB'
			case lcEntidad == 'IMPDIRVAL'
				lcRetorno = 'IDV'
			case lcEntidad == 'IMPDIRART'
				lcRetorno = 'IDA'
			case lcEntidad == 'IMPDIRCLI'
				lcRetorno = 'IDC'
			case lcEntidad == 'IMPDIRPRO'
				lcRetorno = 'IDP'
			case lcEntidad == 'IMPDIRIMP'
				lcRetorno = 'IDI'
			case lcEntidad == 'IMPDIRCAJ'
				lcRetorno = 'IDJ'
			case lcEntidad == 'IMPDIRCON'
				lcRetorno = 'IDO'
			case lcEntidad == 'IMPDIRDES'
				lcRetorno = 'IDD'
			case lcEntidad == 'IMPDIROPE'
				lcRetorno = 'IDT'
			case lcEntidad == 'IMPDIRLIQ'
				lcRetorno = 'IDQ'
			case lcEntidad == 'IMPVERCC'
				lcRetorno = 'IVC'
			case lcEntidad == 'IMPDIRCCA'
				lcRetorno = 'IDX'
			case lcEntidad == 'IMPDIRCCC'
				lcRetorno = 'IDZ'
			case lcEntidad == 'ASIENTOSPERIODICOS'
				lcRetorno = 'RAS'
			case lcEntidad == 'APERTURAEJERCICIO'
				lcRetorno = 'ADE'
			case lcEntidad == 'CONTABILIZACION'
				lcRetorno = 'CAT'
			case lcEntidad == 'ASIENTOTIPO'
				lcRetorno = 'ATI'
			case lcEntidad == 'CIERREEJERCICIO'
				lcRetorno = 'CEJ'
			case lcEntidad == 'ENTREGADEMERCADERIAS'
				lcRetorno = 'EMC'
			case lcEntidad == 'ECOMMERCE'
				lcRetorno = 'ECO'
			case lcEntidad == 'CLIENTEECOMMERCE'
				lcRetorno = 'CEC'
			case lcEntidad == 'OPERACIONECOMMERCE'
				lcRetorno = 'OEC'
			case lcEntidad == 'COMPROBANTESECOMMERCE'
				lcRetorno = 'COE'
			case lcEntidad == 'PUNTOSDEVENTA'
				lcRetorno = 'PVT'
			case lcEntidad == 'DATOSADICIONALESSIPRIB'
				lcRetorno = 'DAS'
			case lcEntidad == 'ARTICULOINCISODATOSADICIONALESSIPRIB'
				lcRetorno = 'ADA'
			case lcEntidad == 'SERVICIOREST'
				lcRetorno = 'RST'
			case lcEntidad == 'CLAVESECRETAREST'
				lcRetorno = 'PKR'
			case lcEntidad == 'AGRUPALISTADOSPERSONALIZADOS'
				lcRetorno = 'ALP'
			case lcEntidad == 'REPORTEAUDITORIACIERREZ'
				lcRetorno = 'ACZ'
			case lcEntidad == 'MOTIVODESCUENTOYDEVOLUCION'
				lcRetorno = 'MDD'
			case lcEntidad == 'CODIGOAUTORIZACIONDJCP'
				lcRetorno = 'DJC'
			case lcEntidad == 'ARQUEODECAJA'
				lcRetorno = 'ARQ'
			case lcEntidad == 'CODIGODESERVICIO'
				lcRetorno = 'COS'
			case lcEntidad == 'TIPODEORDEN'
				lcRetorno = 'TDO'
			case lcEntidad == 'ESTADOSDEINTERACCION'
				lcRetorno = 'EDI'
			case lcEntidad == 'INTERACCIONDEORDEN'
				lcRetorno = 'INO'
			case lcEntidad == 'ENTIDADADICIONAL1'
				lcRetorno = 'EA1'
			case lcEntidad == 'ENTIDADADICIONAL2'
				lcRetorno = 'EA2'
			case lcEntidad == 'ENTIDADADICIONAL3'
				lcRetorno = 'EA3'
			case lcEntidad == 'ORDENDESERVICIO'
				lcRetorno = 'ODS'
			case lcEntidad == 'SELECCIONORDENDESERVICIO'
				lcRetorno = 'SOS'
			case lcEntidad == 'SELECCIONOPERACIONECOMMERCE'
				lcRetorno = 'SOP'
			case lcEntidad == 'GESTIONVENDEDOR'
				lcRetorno = 'GDV'
			case lcEntidad == 'FILTRARCOMPROBANTESACONTROLAR'
				lcRetorno = 'FCC'
			case lcEntidad == 'COTIZACION'
				lcRetorno = 'NCZ'
			case lcEntidad == 'EMAILENCOMPROBANTE'
				lcRetorno = 'EMM'
			case lcEntidad == 'SELECCIONCOMPROBANTEASOCIADO'
				lcRetorno = 'SCA'
			case lcEntidad == 'FACTURAELECTRONICADECREDITO'
				lcRetorno = 'FEM'
			case lcEntidad == 'NOTADECREDITOELECTRONICADECREDITO'
				lcRetorno = 'CEM'
			case lcEntidad == 'NOTADEDEBITOELECTRONICADECREDITO'
				lcRetorno = 'DEM'
			case lcEntidad == 'CONFIRMACIONFECHAVTOMIPYME'
				lcRetorno = 'CFV'
			case lcEntidad == 'NUEVOENTREGAONLINE'
				lcRetorno = 'NEO'
			case lcEntidad == 'SELECCIONDISENOIMPORTACION'
				lcRetorno = 'SDO'
			case lcEntidad == 'ENVIODEMENSAJERIA'
				lcRetorno = 'EME'
			case lcEntidad == 'DATOSTAREAPROGRAMADAECOMMERCE'
				lcRetorno = 'TPE'
			case lcEntidad == 'VALORESENTRANSITO'
				lcRetorno = 'VTR'
			case lcEntidad == 'CONFIRMACIONVALORESENTRANSITO'
				lcRetorno = 'VTC'
			case lcEntidad == 'DATOSTRANSACCIONBANCARIA'
				lcRetorno = 'DTB'
			case lcEntidad == 'REGISTRODECUENTA'
				lcRetorno = 'RCT'
			case lcEntidad == 'TRANSFERENCIAENTRECUENTAS'
				lcRetorno = 'TEC'
			case lcEntidad == 'COMPLETARDATOSREGISTRO'
				lcRetorno = 'DCB'
			case lcEntidad == 'CONCEPTOENTIDADFINANCIERA'
				lcRetorno = 'CEF'
			case lcEntidad == 'MOVIMIENTOBANCARIO'
				lcRetorno = 'MBC'
			case lcEntidad == 'CONCILIACIONES'
				lcRetorno = 'COB'
			case lcEntidad == 'HERRAMIENTACONCILIACION'
				lcRetorno = 'HCB'
			case lcEntidad == 'TIPODECOMPROBANTEDECOMPRA'
				lcRetorno = 'TCC'
			case lcEntidad == 'DEUDADECHEQUES'
				lcRetorno = 'DCH'
			case lcEntidad == 'CHEQUESDISPONIBLES'
				lcRetorno = 'CTD'
			case lcEntidad == 'CODBARRAALTER'
				lcRetorno = 'CAB'
			case lcEntidad == 'PREPARACIONDEMERCADERIA'
				lcRetorno = 'PRM'
			case lcEntidad == 'FACTURAAGRUPADA'
				lcRetorno = 'FAG'
			case lcEntidad == 'NOTADECREDITOAGRUPADA'
				lcRetorno = 'NAG'
			case lcEntidad == 'NOTADEDEBITOAGRUPADA'
				lcRetorno = 'XAD'
			case lcEntidad == 'DATOSADICIONALESSIRE'
				lcRetorno = 'DSI'
			case lcEntidad == 'HERRAMIENTAAGRUPADORADEPACKS'
				lcRetorno = 'PCK'
			case lcEntidad == 'LINKQRENETIQUETA'
				lcRetorno = 'LQR'
			case lcEntidad == 'WEBHOOK'
				lcRetorno = 'WHK'
			case lcEntidad == 'TIQUETDECAMBIO'
				lcRetorno = 'TDC'
			case lcEntidad == 'PERSONALIZACIONDEENTIDADES'
				lcRetorno = 'PEN'
			case lcEntidad == 'DIRECCIONENTREGAENCOMPROBANTE'
				lcRetorno = 'DIE'
			case lcEntidad == 'REGISTROLIQUIDACIONCONSIGNACIONES'
				lcRetorno = 'RLC'
			case lcEntidad == 'FECHACANCELACION'
				lcRetorno = 'FEC'
			case lcEntidad == 'MARCA'
				lcRetorno = 'MAR'
			case lcEntidad == 'ETIQUETASECOMMERCE'
				lcRetorno = 'ETE'
			case lcEntidad == 'CATEGORIASECOMMERCE'
				lcRetorno = 'CTG'
			case lcEntidad == 'CONFIGURACIONARTICULOECOMMERCE'
				lcRetorno = 'CED'
			case lcEntidad == 'CATEGORIASGOOGLESHOPPING'
				lcRetorno = 'CGS'
			case lcEntidad == 'APERTURAAUTOMATICAENTIDADES'
				lcRetorno = 'AAE'
			case lcEntidad == 'OPEECOMENPROCESO'
				lcRetorno = 'CY3'
			case lcEntidad == 'CAEA'
				lcRetorno = 'OCA'
			case lcEntidad == 'CAEAINFORMA'
				lcRetorno = 'IMC'
			case lcEntidad == 'MAQUINARIA'
				lcRetorno = 'MQP'
			case lcEntidad == 'CONSUMOPRODUCCION'
				lcRetorno = 'CSM'
			case lcEntidad == 'CLASIFICACIONPRODUCCION'
				lcRetorno = 'CLP'
			case lcEntidad == 'RUBROPRODUCCION'
				lcRetorno = 'RBP'
			case lcEntidad == 'TIPIFICACIONPRODUCCION1'
				lcRetorno = 'TP1'
			case lcEntidad == 'TIPIFICACIONPRODUCCION2'
				lcRetorno = 'TP2'
			case lcEntidad == 'VENDEDORENCOMPROBANTE'
				lcRetorno = 'VEC'
			case lcEntidad == 'CONDICIONDEPAGOENCOMPROBANTE'
				lcRetorno = 'ECP'
			case lcEntidad == 'INVENTARIO'
				lcRetorno = 'INV'
			case lcEntidad == 'INSUMO'
				lcRetorno = 'INP'
			case lcEntidad == 'CURVADEPRODUCCION'
				lcRetorno = 'CVP'
			case lcEntidad == 'MOTIVODESCARTE'
				lcRetorno = 'MDE'
			case lcEntidad == 'TALLER'
				lcRetorno = 'TLL'
			case lcEntidad == 'PROCESOPRODUCCION'
				lcRetorno = 'PRP'
			case lcEntidad == 'FILTRARCOMPROBANTESAINSERTAR'
				lcRetorno = 'FCI'
			case lcEntidad == 'SELECOMPAINSERTAR'
				lcRetorno = 'SCI'
			case lcEntidad == 'INFORMEVENTASLPS'
				lcRetorno = 'IVS'
			case lcEntidad == 'SELECCHEQUETERCEROS'
				lcRetorno = 'SCT'
			case lcEntidad == 'SELECHEQUEAINSERTAR'
				lcRetorno = 'SCH'
			case lcEntidad == 'RETIRODEEFECTIVO'
				lcRetorno = 'RDE'
			case lcEntidad == 'GESTIONCHCUSTODIA'
				lcRetorno = 'GCC'
			case lcEntidad == 'GENERADORTOKEN'
				lcRetorno = 'CPT'
			case lcEntidad == 'LISTADECOSTOSDEPRODUCCION'
				lcRetorno = 'LCP'
			case lcEntidad == 'MODIFICACIONDECOSTOSDEPRODUCCION'
				lcRetorno = 'MCP'
			case lcEntidad == 'COTIZACIONGESTIONDEORDENDEPRODUCCION'
				lcRetorno = 'CGO'
			case lcEntidad == 'LIQUIDACIONDETALLER'
				lcRetorno = 'LTP'
			case lcEntidad == 'COSTODEINSUMO'
				lcRetorno = '026'
			case lcEntidad == 'PROCESARNCPENDIENTEPROMOBANCO'
				lcRetorno = 'PCB'
			case lcEntidad == 'ALIVIODECAJA'
				lcRetorno = 'ADC'
			case lcEntidad == 'ADT_ARTICULO'
				lcRetorno = 'AUD001'
			case lcEntidad == 'ADT_STOCKCOMBINACION'
				lcRetorno = 'AUD012'
			case lcEntidad == 'ADT_PRECIODEARTICULO'
				lcRetorno = 'AUD018'
			case lcEntidad == 'ADT_STOCKARTICULOS'
				lcRetorno = 'AUD024'
			case lcEntidad == 'ADT_DESCUENTO'
				lcRetorno = 'AUDDES'
			case lcEntidad == 'ADT_CONSUMOCLIENTE'
				lcRetorno = 'AUDCCL'
			case lcEntidad == 'ADT_LIMITECONSUMO'
				lcRetorno = 'AUDLCN'
			case lcEntidad == 'ADT_ESTADOCONTROLADORFISCAL'
				lcRetorno = 'AUD140'
		endcase

		return lcRetorno
	endfunc

enddefine