
define class Din_ObjetoCursorAtributosConSaltoDeCampo as ZooSession
	cCursorAtributos = ''
	cCursorAtributosForaneos = ''

	*------------------------------------------------------------------------------------
	Function ObtenerCursorAtributosConSaltoDeCampo() as string
		with this
								.cCursorAtributos = 'c_cbo_AtributosConSalto' + sys( 2015 )
							if !used( .cCursorAtributos )
								create cursor ( .cCursorAtributos ) ( Etiqueta c( 53 ) , Atributo c( 40 ) , Entidad c( 40 ) , Detalle c( 40 ) , ValorSugerido c( 254 ) , Obligatorio L , dominio c( 30 ) , ValorDelCombo c( 254 ) , ClaveForanea c( 40 ) , AtributoForaneo c( 60 ) , EtiquetaAdn c( 53 ) , ClavePrimaria L  )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [. - Color (Carácter)], [COLOR], [ARTICULO], [ParticipantesDetalle], [], .F., [CODIGO], [ARTICULOPARTICIPANTESDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Color (Carácter)], [F_COLOR_DESDE], [CALCULODEPRECIOS], [], [], .F., [EtiquetaCaracterDesdeHastaBusc], [CALCULODEPRECIOSF_COLOR_DESDE], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Color (Carácter)], [F_COLOR_HASTA], [CALCULODEPRECIOS], [], [ZZ], .F., [EtiquetaCaracterDesdeHastaBusc], [CALCULODEPRECIOSF_COLOR_HASTA], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Dimensiones ecommerce por variante - Color (Carácter)], [COLOR], [CONFIGURACIONARTICULOECOMMERCE], [DimensionesEcom], [], .F., [CODIGO], [CONFIGURACIONARTICULOECOMMERCEDIMENSIONESECOMCOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Color del concepto para envío (Carácter)], [CONCCOLOR], [ECOMMERCE], [], [], .F., [CODIGO], [ECOMMERCECONCCOLOR], [COLOR], [], [Color del concepto para envío], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Color (Carácter)], [COLOR], [EQUIVALENCIA], [], [], .T., [CODIGO], [EQUIVALENCIACOLOR], [Color], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Articulos Señados - Color (Carácter)], [COLOR], [FACTURA], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [FACTURAARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos - Color (Carácter)], [COLOR], [FACTURAAGRUPADA], [FacturaDetalle], [], .F., [CODIGO], [FACTURAAGRUPADAFACTURADETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos señados - Color (Carácter)], [COLOR], [FACTURAAGRUPADA], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [FACTURAAGRUPADAARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Articulos Señados - Color (Carácter)], [COLOR], [FACTURADEEXPORTACION], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [FACTURADEEXPORTACIONARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Articulos Señados - Color (Carácter)], [COLOR], [FACTURAELECTRONICA], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [FACTURAELECTRONICAARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos - Color (Carácter)], [COLOR], [FACTURAELECTRONICADECREDITO], [FacturaDetalle], [], .F., [CODIGO], [FACTURAELECTRONICADECREDITOFACTURADETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos señados - Color (Carácter)], [COLOR], [FACTURAELECTRONICADECREDITO], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [FACTURAELECTRONICADECREDITOARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Articulos Señados - Color (Carácter)], [COLOR], [FACTURAELECTRONICAEXPORTACION], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [FACTURAELECTRONICAEXPORTACIONARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Detalle Imp. Etiqueta - Color (Carácter)], [COLOR], [IMPRESIONDEETIQUETA], [ETIQUETADETALLE], [], .F., [CODIGO], [IMPRESIONDEETIQUETAETIQUETADETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Color (Carácter)], [COLOR], [LINKQRENETIQUETA], [], [], .F., [CODIGO], [LINKQRENETIQUETACOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos - Color (Carácter)], [COLOR], [MERCADERIAENTRANSITO], [MovimientoDetalle], [], .F., [CODIGO], [MERCADERIAENTRANSITOMOVIMIENTODETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Combinaciones - Color (Carácter)], [COLOR], [MINIMOREPOSICION], [MinRepo], [], .F., [CODIGO], [MINIMOREPOSICIONMINREPOCOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Precios de artículos - Color (Carácter)], [COLOR], [MODIFICACIONPRECIOS], [ModPrecios], [], .F., [CODIGO], [MODIFICACIONPRECIOSMODPRECIOSCOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Articulos Señados - Color (Carácter)], [COLOR], [NOTADECREDITO], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [NOTADECREDITOARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos - Color (Carácter)], [COLOR], [NOTADECREDITOAGRUPADA], [FacturaDetalle], [], .F., [CODIGO], [NOTADECREDITOAGRUPADAFACTURADETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos señados - Color (Carácter)], [COLOR], [NOTADECREDITOAGRUPADA], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [NOTADECREDITOAGRUPADAARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Articulos Señados - Color (Carácter)], [COLOR], [NOTADECREDITODEEXPORTACION], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [NOTADECREDITODEEXPORTACIONARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Articulos Señados - Color (Carácter)], [COLOR], [NOTADECREDITOELECTRONICA], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [NOTADECREDITOELECTRONICAARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos - Color (Carácter)], [COLOR], [NOTADECREDITOELECTRONICADECREDITO], [FacturaDetalle], [], .F., [CODIGO], [NOTADECREDITOELECTRONICADECREDITOFACTURADETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos señados - Color (Carácter)], [COLOR], [NOTADECREDITOELECTRONICADECREDITO], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [NOTADECREDITOELECTRONICADECREDITOARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Articulos Señados - Color (Carácter)], [COLOR], [NOTADECREDITOELECTRONICAEXPORTACION], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [NOTADECREDITOELECTRONICAEXPORTACIONARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos - Color (Carácter)], [COLOR], [NOTADEDEBITOAGRUPADA], [FacturaDetalle], [], .F., [CODIGO], [NOTADEDEBITOAGRUPADAFACTURADETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Articulos Señados - Color (Carácter)], [COLOR], [NOTADEDEBITODEEXPORTACION], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [NOTADEDEBITODEEXPORTACIONARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos - Color (Carácter)], [COLOR], [NOTADEDEBITOELECTRONICADECREDITO], [FacturaDetalle], [], .F., [CODIGO], [NOTADEDEBITOELECTRONICADECREDITOFACTURADETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Articulos Señados - Color (Carácter)], [COLOR], [NOTADEDEBITOELECTRONICAEXPORTACION], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [NOTADEDEBITOELECTRONICAEXPORTACIONARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Operación detalle - Color (Carácter)], [COLOR], [OPERACIONECOMMERCE], [PublicacionDetalle], [], .F., [CODIGO], [OPERACIONECOMMERCEPUBLICACIONDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Color (Carácter)], [COLOR], [ORDENDESERVICIO], [], [], .F., [CODIGO], [ORDENDESERVICIOCOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos controlados - Color (Carácter)], [COLOR], [PICKING], [DetalleControlado], [], .F., [CODIGO], [PICKINGDETALLECONTROLADOCOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Color (Carácter)], [F_COLOR_DESDE], [PRECARGAETIART], [], [], .F., [EtiquetaCaracterDesdeHastaBusc], [PRECARGAETIARTF_COLOR_DESDE], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Color (Carácter)], [F_COLOR_HASTA], [PRECARGAETIART], [], [ZZ], .F., [EtiquetaCaracterDesdeHastaBusc], [PRECARGAETIARTF_COLOR_HASTA], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos del pedido - Color (Carácter)], [COLOR], [PREPARACIONDEMERCADERIA], [FacturaDetalle], [], .F., [CODIGO], [PREPARACIONDEMERCADERIAFACTURADETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Color desde (Carácter)], [ITEM_COLOR_DESDE], [SELECCIONOPERACIONECOMMERCE], [], [], .F., [EtiquetaCaracterDesdeHastaBusc], [SELECCIONOPERACIONECOMMERCEITEM_COLOR_DESDE], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Color hasta (Carácter)], [ITEM_COLOR_HASTA], [SELECCIONOPERACIONECOMMERCE], [], [ZZZZZZ], .F., [EtiquetaCaracterDesdeHastaBusc], [SELECCIONOPERACIONECOMMERCEITEM_COLOR_HASTA], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos señados - Color (Carácter)], [COLOR], [SENIA], [ArticulosDetalle], [], .F., [CODIGO], [SENIAARTICULOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Articulos Señados - Color (Carácter)], [COLOR], [TICKETFACTURA], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [TICKETFACTURAARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Articulos Señados - Color (Carácter)], [COLOR], [TICKETNOTADECREDITO], [ArticulosSeniadosDetalle], [], .F., [CODIGO], [TICKETNOTADECREDITOARTICULOSSENIADOSDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Color (Carácter)], [COLOR], [TIDIFERENCIASDEINVENTARIODETALLE], [], [], .F., [CODIGO], [TIDIFERENCIASDEINVENTARIODETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Color (Carácter)], [COLOR], [TIINVENTARIOACONTDETALLE], [], [], .F., [CODIGO], [TIINVENTARIOACONTDETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Color (Carácter)], [COLOR], [TIINVENTARIOFISICODETALLE], [], [], .F., [CODIGO], [TIINVENTARIOFISICODETALLECOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Color (Carácter)], [COLOR], [TIINVENTARIOFISICODETALLETMP], [], [], .F., [CODIGO], [TIINVENTARIOFISICODETALLETMPCOLOR], [COLOR], [], [Color], .F. )
								insert into ( .cCursorAtributos ) ( Etiqueta, Atributo, Entidad, Detalle, ValorSugerido, Obligatorio, Dominio, ValorDelCombo, ClaveForanea, AtributoForaneo, EtiquetaAdn, ClavePrimaria ) values ( [Artículos para cambio - Color (Carácter)], [COLOR], [TIQUETDECAMBIO], [DetalleComprobante], [], .F., [CODIGO], [TIQUETDECAMBIODETALLECOMPROBANTECOLOR], [COLOR], [], [Color], .F. )
							endif

		endwith
		return this.cCursorAtributos 
	endfunc
	*------------------------------------------------------------------------------------
	Function ObtenerCursorAtributosForaneos() as string
		with this
			this.cCursorAtributosForaneos = 'c_' + sys(2015)
			if !used( .cCursorAtributosForaneos )
				create cursor ( .cCursorAtributosForaneos ) ( EntidadItem c( 40 ), AtributoItem c( 60 ), ClaveForanea c( 40 ), Entidad c( 40 ), AtributoEntidad c( 40 ) )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMAJUSTEDEESTADOS], [ColorDetalle], [COLOR], [AJUSTEDEESTADOS], [StockAfectado] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMAJESTADOSAUDCOMB], [ColorDetalle], [COLOR], [AJUSTEDEESTADOS], [StockAfectadoAuditoriaComb] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMAJUSTECOMPROBANTES], [ColorDetalle], [COLOR], [AJUSTEDEESTADOS], [ComprobantesModificados] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMAJUSTEDESTOCK], [ColorDetalle], [COLOR], [AJUSTEDESTOCK], [stockafectado] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMAJAUDICOMBINACION], [ColorDetalle], [COLOR], [AJUSTEDESTOCK], [StockAfectadoAuditoriaComb] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMAJUSTOCKENTRANSITO], [ColorDetalle], [COLOR], [AJUSTEDESTOCK], [stockafectadoEnTransito] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMAJAUDIENTRANSITO], [ColorDetalle], [COLOR], [AJUSTEDESTOCK], [StockAfectadoAuditoriaEnTransito] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMPARTICIPANTES], [ColorDetalle], [COLOR], [ARTICULO], [ParticipantesDetalle] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMDIMENSIONESECOM], [ColorDetalle], [COLOR], [CONFIGURACIONARTICULOECOMMERCE], [DimensionesEcom] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMAGRUPADORDEPACK], [ColorDetalle], [COLOR], [HERRAMIENTAAGRUPADORADEPACKS], [DetallePacks] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMMERCENTRANSITO], [ColorDetalle], [COLOR], [MERCADERIAENTRANSITO], [MovimientoDetalle] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMMINIMOREPOSICION], [ColorDetalle], [COLOR], [MINIMOREPOSICION], [MinRepo] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMMODCOSTOPROD], [ColorDetalle], [COLOR], [MODIFICACIONDECOSTOSDEPRODUCCION], [ModCostos] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMMODIFICACIONPRECIOS], [ColorDetalle], [COLOR], [MODIFICACIONPRECIOS], [ModPrecios] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMPUBLICACIONECOM], [ColorDetalle], [COLOR], [OPERACIONECOMMERCE], [PublicacionDetalle] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMDIFERENCIASPICKING], [ColorDetalle], [COLOR], [PICKING], [DetalleDiferencias] )
				insert into ( .cCursorAtributosForaneos ) ( EntidadItem, AtributoItem, ClaveForanea, Entidad, AtributoEntidad ) values ( [ITEMTIQUETDECAMBIO], [ColorDetalle], [COLOR], [TIQUETDECAMBIO], [DetalleComprobante] )
			endif
		endwith
		return this.cCursorAtributosForaneos 
	endfunc

enddefine