
define class Din_Datosdeentidades as Custom

	*-----------------------------------------------------------------------------------------
	function ObtenerIdentificadorDeEntidad( tcEntidad as string ) as string
		local lcRetorno as string, lcEntidad as string
		lcRetorno = ''
		lcEntidad = upper( alltrim( tcEntidad ) )
		do case
			case lcEntidad == 'COLOR'
				lcRetorno = '001'
			case lcEntidad == 'PAISES'
				lcRetorno = 'PAI'
			case lcEntidad == 'PROVINCIA'
				lcRetorno = 'PRO'
			case lcEntidad == 'VENDEDOR'
				lcRetorno = 'VEN'
			case lcEntidad == 'ARTICULO'
				lcRetorno = 'ART'
			case lcEntidad == 'PROVEEDOR'
				lcRetorno = 'PRV'
			case lcEntidad == 'MONEDA'
				lcRetorno = 'MON'
			case lcEntidad == 'VALOR'
				lcRetorno = 'VAL'
			case lcEntidad == 'GRUPOVALOR'
				lcRetorno = 'GPV'
			case lcEntidad == 'CONCEPTOCAJA'
				lcRetorno = 'CCA'
			case lcEntidad == 'LISTADEPRECIOS'
				lcRetorno = 'LPR'
			case lcEntidad == 'CLIENTE'
				lcRetorno = 'CLI'
			case lcEntidad == 'ENTIDADFINANCIERA'
				lcRetorno = 'ENF'
			case lcEntidad == 'MOTIVO'
				lcRetorno = 'MOT'
			case lcEntidad == 'ORIGENDEDATOS'
				lcRetorno = '010'
			case lcEntidad == 'FACTURA'
				lcRetorno = 'FCV'
			case lcEntidad == 'AGRUPAMIENTO'
				lcRetorno = 'AGR'
			case lcEntidad == 'AGRUPAMIENTOPORCOMPANIA'
				lcRetorno = 'AGC'
			case lcEntidad == 'MATERIAL'
				lcRetorno = '003'
			case lcEntidad == 'TALONARIO'
				lcRetorno = 'TAL'
			case lcEntidad == 'NUMERACIONES'
				lcRetorno = 'NUM'
			case lcEntidad == 'COMPROBANTEDECAJA'
				lcRetorno = 'COC'
			case lcEntidad == 'NOTADECREDITO'
				lcRetorno = 'NCV'
			case lcEntidad == 'NOTADEDEBITO'
				lcRetorno = 'NDV'
			case lcEntidad == 'TICKETFACTURA'
				lcRetorno = 'TFC'
			case lcEntidad == 'TICKETNOTADECREDITO'
				lcRetorno = 'TNC'
			case lcEntidad == 'TICKETNOTADEDEBITO'
				lcRetorno = 'TND'
			case lcEntidad == 'STOCKARTICULOS'
				lcRetorno = '024'
			case lcEntidad == 'CAJAAUDITORIA'
				lcRetorno = 'CAA'
			case lcEntidad == 'CAJAESTADO'
				lcRetorno = 'CAE'
			case lcEntidad == 'CAJASALDOS'
				lcRetorno = 'CAS'
			case lcEntidad == 'MOVIMIENTODECAJA'
				lcRetorno = 'MCA'
			case lcEntidad == 'CTACTE'
				lcRetorno = '053'
			case lcEntidad == 'BUZON'
				lcRetorno = 'BUZ'
			case lcEntidad == 'INFORMACIONADICIONALCOMPVTAS'
				lcRetorno = '049'
			case lcEntidad == 'MEMORIA'
				lcRetorno = 'MEM'
			case lcEntidad == 'TALLE'
				lcRetorno = '150'
			case lcEntidad == 'TEMPORADA'
				lcRetorno = '153'
			case lcEntidad == 'MODIFICACIONPRECIOS'
				lcRetorno = 'PRE'
			case lcEntidad == 'MOVIMIENTODESTOCK'
				lcRetorno = 'MDS'
			case lcEntidad == 'PRECIODEARTICULO'
				lcRetorno = '018'
			case lcEntidad == 'STOCKCOMBINACION'
				lcRetorno = '012'
			case lcEntidad == 'CLASIFICACIONCLIENTE'
				lcRetorno = '203'
			case lcEntidad == 'DISENOIMPRESION'
				lcRetorno = 'IMP'
			case lcEntidad == 'TIPOAREAIMPRESION'
				lcRetorno = 'ARE'
			case lcEntidad == 'ESTILOIMPRESION'
				lcRetorno = 'ESI'
			case lcEntidad == 'TIPOATRIBUTOIMPRESION'
				lcRetorno = 'ATR'
			case lcEntidad == 'EQUIVALENCIA'
				lcRetorno = 'CBA'
			case lcEntidad == 'REDONDEODEPRECIOS'
				lcRetorno = 'RED'
			case lcEntidad == 'DISENOIMPO'
				lcRetorno = 'DIM'
			case lcEntidad == 'DISENOEXPO'
				lcRetorno = 'EXP'
			case lcEntidad == 'CONDICIONIMPO'
				lcRetorno = 'CON'
			case lcEntidad == 'FORMATOEXPORTACION'
				lcRetorno = 'FOE'
			case lcEntidad == 'TIPOAREAEXPORTACION'
				lcRetorno = 'TAE'
			case lcEntidad == 'TIPOATRIBUTOSEXPORTACION'
				lcRetorno = 'TBE'
			case lcEntidad == 'TIPOARCHIVOEXPORTACION'
				lcRetorno = 'THE'
			case lcEntidad == 'TIPOREGISTROEXPORTACION'
				lcRetorno = 'TRE'
			case lcEntidad == 'CONVERSION'
				lcRetorno = 'CDE'
			case lcEntidad == 'CONVERSIONVALORES'
				lcRetorno = 'VCE'
			case lcEntidad == 'IMPOAGRUPADAS'
				lcRetorno = 'IMA'
			case lcEntidad == 'EXPOAGRUPADAS'
				lcRetorno = 'EXA'
			case lcEntidad == 'TIPOARCHIVOIMPORTACION'
				lcRetorno = 'THI'
			case lcEntidad == 'DATOSFISCALES'
				lcRetorno = 'DFI'
			case lcEntidad == 'JURISDICCION'
				lcRetorno = 'JUR'
			case lcEntidad == 'TIINVENTARIOACONT'
				lcRetorno = 'TIT'
			case lcEntidad == 'TIINVENTARIOACONTDETALLE'
				lcRetorno = 'ITD'
			case lcEntidad == 'TIINVENTARIOFISICO'
				lcRetorno = 'TIF'
			case lcEntidad == 'TIINVENTARIOFISICODETALLE'
				lcRetorno = 'FIT'
			case lcEntidad == 'TIDIFERENCIASDEINVENTARIO'
				lcRetorno = 'TIN'
			case lcEntidad == 'TIDIFERENCIASDEINVENTARIODETALLE'
				lcRetorno = 'TID'
			case lcEntidad == 'MERCADERIAENTRANSITO'
				lcRetorno = 'MTR'
			case lcEntidad == 'PADRONIIBB'
				lcRetorno = 'IIB'
			case lcEntidad == 'CAI'
				lcRetorno = 'CAI'
			case lcEntidad == 'REMITO'
				lcRetorno = 'RMV'
			case lcEntidad == 'SCRIPT'
				lcRetorno = 'SCR'
			case lcEntidad == 'SELECCIONDISENOIMPRESION'
				lcRetorno = 'SDI'
			case lcEntidad == 'CONSUMOCLIENTE'
				lcRetorno = 'CCL'
			case lcEntidad == 'VALEDECAMBIO'
				lcRetorno = 'VCB'
			case lcEntidad == 'LIMITECONSUMO'
				lcRetorno = 'LCN'
			case lcEntidad == 'DESCUENTO'
				lcRetorno = 'DES'
			case lcEntidad == 'REGLASTRANSFERENCIAS'
				lcRetorno = 'RTR'
			case lcEntidad == 'CODIGOPOSTAL'
				lcRetorno = 'CP8'
			case lcEntidad == 'ACCIONESAUTOMATICAS'
				lcRetorno = 'AA'
			case lcEntidad == 'UNIDADDEMEDIDA'
				lcRetorno = 'UDM'
			case lcEntidad == 'FAMILIA'
				lcRetorno = 'FML'
			case lcEntidad == 'LINEA'
				lcRetorno = 'LIN'
			case lcEntidad == 'GRUPO'
				lcRetorno = 'GRP'
			case lcEntidad == 'CATEGORIADEARTICULO'
				lcRetorno = 'SGR'
			case lcEntidad == 'CLASIFICACIONARTICULO'
				lcRetorno = '205'
			case lcEntidad == 'TIPODEARTICULO'
				lcRetorno = '206'
			case lcEntidad == 'DEVOLUCION'
				lcRetorno = 'DEV'
			case lcEntidad == 'CLASIFICACIONPROVEEDOR'
				lcRetorno = '207'
			case lcEntidad == 'CLASIFICACIONVENDEDOR'
				lcRetorno = '208'
			case lcEntidad == 'RECIBO'
				lcRetorno = 'REC'
			case lcEntidad == 'AJUSTEDESTOCK'
				lcRetorno = 'AJS'
			case lcEntidad == 'IMPRESIONDEETIQUETA'
				lcRetorno = 'IET'
			case lcEntidad == 'SENIAPENDIENTE'
				lcRetorno = 'SEP'
			case lcEntidad == 'SENIA'
				lcRetorno = 'SEN'
			case lcEntidad == 'CHEQUE'
				lcRetorno = 'CH'
			case lcEntidad == 'DISENOTRANSFORMACIONLINCE'
				lcRetorno = 'DTL'
			case lcEntidad == 'PEDIDO'
				lcRetorno = 'PED'
			case lcEntidad == 'PRESUPUESTO'
				lcRetorno = 'PR1'
			case lcEntidad == 'TRANSPORTISTA'
				lcRetorno = 'TRA'
			case lcEntidad == 'FACTURADECOMPRA'
				lcRetorno = 'FDC'
			case lcEntidad == 'TIPOIMPUESTO'
				lcRetorno = 'TIM'
			case lcEntidad == 'CONDICIONDEPAGO'
				lcRetorno = 'CDP'
			case lcEntidad == 'IMPUESTO'
				lcRetorno = 'IMS'
			case lcEntidad == 'CALCULODEPRECIOS'
				lcRetorno = '041'
			case lcEntidad == 'OPERADORADETARJETA'
				lcRetorno = '056'
			case lcEntidad == 'CIERREDELOTE'
				lcRetorno = '057'
			case lcEntidad == 'POS'
				lcRetorno = 'POS'
			case lcEntidad == 'CUPON'
				lcRetorno = 'CUP'
			case lcEntidad == 'DATOSTARJETA'
				lcRetorno = 'DP2'
			case lcEntidad == 'TRATAMIENTOCOMPROBANTES'
				lcRetorno = 'TCO'
			case lcEntidad == 'CAE'
				lcRetorno = 'FAE'
			case lcEntidad == 'EQUIVALORLINCE'
				lcRetorno = 'EVL'
			case lcEntidad == 'FACTURAELECTRONICA'
				lcRetorno = 'FEN'
			case lcEntidad == 'NOTADECREDITOELECTRONICA'
				lcRetorno = 'CEN'
			case lcEntidad == 'NOTADEDEBITOELECTRONICA'
				lcRetorno = 'DEN'
			case lcEntidad == 'FAVORITOLISTADOS'
				lcRetorno = 'FVX'
			case lcEntidad == 'CAEPORLOTE'
				lcRetorno = 'OFA'
			case lcEntidad == 'ZUDESCARGALAN'
				lcRetorno = 'LAN'
			case lcEntidad == 'INFORMACIONLISTADOS'
				lcRetorno = 'IAL'
			case lcEntidad == 'BASEDEDATOS'
				lcRetorno = '052'
			case lcEntidad == 'CTACTECOMPRA'
				lcRetorno = '130'
			case lcEntidad == 'ORDENDEPAGO'
				lcRetorno = 'ODP'
			case lcEntidad == 'COMPORTAMIENTOCODIGOSUGERIDOENTIDAD'
				lcRetorno = 'CCS'
			case lcEntidad == 'NOTADEDEBITOCOMPRA'
				lcRetorno = 'NDC'
			case lcEntidad == 'NOTADECREDITOCOMPRA'
				lcRetorno = 'NCC'
			case lcEntidad == 'SUCURSALBANCARIA'
				lcRetorno = '131'
			case lcEntidad == 'CUENTABANCARIA'
				lcRetorno = '132'
			case lcEntidad == 'CHEQUERA'
				lcRetorno = '133'
			case lcEntidad == 'CHEQUEPROPIO'
				lcRetorno = 'CP'
			case lcEntidad == 'ESTADOCONTROLADORFISCAL'
				lcRetorno = '140'
			case lcEntidad == 'CORREDOR'
				lcRetorno = 'COR'
			case lcEntidad == 'MOVIMIENTOSINTERNOSLINCE'
				lcRetorno = 'MIT'
			case lcEntidad == 'CUPONESPENDIENTES'
				lcRetorno = 'CPN'
			case lcEntidad == 'CANJEDECUPONES'
				lcRetorno = 'CDV'
			case lcEntidad == 'FACTURAELECTRONICAEXPORTACION'
				lcRetorno = 'FEE'
			case lcEntidad == 'INCOTERMS'
				lcRetorno = 'INT'
			case lcEntidad == 'UNIDADDEMEDIDAAFIP'
				lcRetorno = 'EUM'
			case lcEntidad == 'PAISAFIP'
				lcRetorno = 'PAF'
			case lcEntidad == 'MONEDAAFIP'
				lcRetorno = 'MAF'
			case lcEntidad == 'NOTADECREDITOELECTRONICAEXPORTACION'
				lcRetorno = 'CEE'
			case lcEntidad == 'NOTADEDEBITOELECTRONICAEXPORTACION'
				lcRetorno = 'DEE'
			case lcEntidad == 'AGRUPAMIENTODEBUZONES'
				lcRetorno = 'ABZ'
			case lcEntidad == 'IMPRIMIRCOMPROBANTEPORLOTE'
				lcRetorno = 'IPL'
			case lcEntidad == 'PALETADECOLORES'
				lcRetorno = 'PTC'
			case lcEntidad == 'CURVADETALLES'
				lcRetorno = 'CDT'
			case lcEntidad == 'FORMULA'
				lcRetorno = 'FOR'
			case lcEntidad == 'SALTODECAMPO'
				lcRetorno = 'SDC'
			case lcEntidad == 'COMISION'
				lcRetorno = 'COM'
			case lcEntidad == 'SUCURSAL'
				lcRetorno = 'SUC'
			case lcEntidad == 'TIPOSUCURSAL'
				lcRetorno = 'TSU'
			case lcEntidad == 'LINEASUCURSAL'
				lcRetorno = 'LSU'
			case lcEntidad == 'SEGMENTACION'
				lcRetorno = 'SEG'
			case lcEntidad == 'CLASEDETARJETA'
				lcRetorno = 'CLA'
			case lcEntidad == 'TIINVENTARIOFISICODETALLETMP'
				lcRetorno = 'FTT'
			case lcEntidad == 'PICKING'
				lcRetorno = 'PIK'
			case lcEntidad == 'OBJETIVOSVENTA'
				lcRetorno = 'OBJ'
			case lcEntidad == 'TIPOOBJETIVO'
				lcRetorno = 'TOB'
			case lcEntidad == 'MINIMOREPOSICION'
				lcRetorno = 'MIN'
			case lcEntidad == 'LISTADOSPERSONALIZADOS'
				lcRetorno = 'LPZ'
			case lcEntidad == 'REGISTRODEMANTENIMIENTO'
				lcRetorno = 'RAM'
			case lcEntidad == 'PROMOCION'
				lcRetorno = 'PR0'
			case lcEntidad == 'SELECCIONPARAINSERTAR'
				lcRetorno = 'SEI'
			case lcEntidad == 'PAGO'
				lcRetorno = 'PAG'
			case lcEntidad == 'AJUSTEDEESTADOS'
				lcRetorno = 'AES'
			case lcEntidad == 'COMPROBANTEDERETENCIONES'
				lcRetorno = 'CDR'
			case lcEntidad == 'CONVENIOMULTILATERAL'
				lcRetorno = 'CML'
			case lcEntidad == 'PRESUPUESTODECOMPRA'
				lcRetorno = 'PDC'
			case lcEntidad == 'PEDIDODECOMPRA'
				lcRetorno = 'PCO'
			case lcEntidad == 'SOLICITUDDECOMPRA'
				lcRetorno = 'SOC'
			case lcEntidad == 'REMITODECOMPRA'
				lcRetorno = 'RDC'
			case lcEntidad == 'CANCELACIONDECOMPRA'
				lcRetorno = 'CAC'
			case lcEntidad == 'REQUERIMIENTODECOMPRA'
				lcRetorno = 'REQ'
			case lcEntidad == 'PROPIEDADESLISTADOS'
				lcRetorno = 'PLI'
			case lcEntidad == 'AJUSTEDECUPON'
				lcRetorno = 'AJC'
			case lcEntidad == 'ERRORESCFIBM4610KC4'
				lcRetorno = 'KC4'
			case lcEntidad == 'BOLSASYCAJAS'
				lcRetorno = 'BYC'
			case lcEntidad == 'AJUSTECCCLIENTE'
				lcRetorno = 'AJU'
			case lcEntidad == 'AJUSTECCPROVEEDOR'
				lcRetorno = 'AJP'
			case lcEntidad == 'CANCELACIONDESENIAS'
				lcRetorno = 'CDS'
			case lcEntidad == 'GTIN'
				lcRetorno = 'GTI'
			case lcEntidad == 'SITUACIONFISCAL'
				lcRetorno = 'STF'
			case lcEntidad == 'PASAJEDESTOCK'
				lcRetorno = 'PST'
			case lcEntidad == 'SELECCIONBASESARCHIVADAS'
				lcRetorno = 'SBA'
			case lcEntidad == 'PRECARGAETIART'
				lcRetorno = 'PET'
			case lcEntidad == 'NUEVOENBASEA'
				lcRetorno = 'NBA'
			case lcEntidad == 'REGISTRODEACTIVIDAD'
				lcRetorno = 'ACT'
			case lcEntidad == 'CONCILIACIONDECAJA'
				lcRetorno = 'CCJ'
			case lcEntidad == 'POOLDECLASE'
				lcRetorno = 'POO'
			case lcEntidad == 'ACCESOAOBJETO'
				lcRetorno = 'AO'
			case lcEntidad == 'LISTADEPRECIOSCALCULADA'
				lcRetorno = 'LPC'
			case lcEntidad == 'EXPRESIONLISTADOPERSONALIZADO'
				lcRetorno = 'ELP'
			case lcEntidad == 'CUPONESHUERFANOS'
				lcRetorno = 'CPH'
			case lcEntidad == 'NOMENCLADORARBA'
				lcRetorno = 'NAR'
			case lcEntidad == 'UNIDADDEMEDIDAARBA'
				lcRetorno = 'UMA'
			case lcEntidad == 'REMITOELECTRONICO'
				lcRetorno = 'REL'
			case lcEntidad == 'DESTINODESCARGACHEQUES'
				lcRetorno = 'DDC'
			case lcEntidad == 'DESCARGADECHEQUES'
				lcRetorno = 'DCT'
			case lcEntidad == 'FACTURADEEXPORTACION'
				lcRetorno = 'FMX'
			case lcEntidad == 'NOTADECREDITODEEXPORTACION'
				lcRetorno = 'NCX'
			case lcEntidad == 'NOTADEDEBITODEEXPORTACION'
				lcRetorno = 'NDX'
			case lcEntidad == 'EDICIONIMPUESTOIVACOMPRAS'
				lcRetorno = 'EIC'
			case lcEntidad == 'NOMBREDEFANTASIA'
				lcRetorno = 'NFA'
			case lcEntidad == 'TIPODEDIRECCION'
				lcRetorno = 'TDD'
			case lcEntidad == 'CONTACTO'
				lcRetorno = 'CNT'
			case lcEntidad == 'TIPOCLIENTE'
				lcRetorno = 'TCL'
			case lcEntidad == 'CATEGORIACLIENTE'
				lcRetorno = 'CGC'
			case lcEntidad == 'REGISTRODEBAJA'
				lcRetorno = 'RBL'
			case lcEntidad == 'DISCOVER'
				lcRetorno = 'DSC'
			case lcEntidad == 'CRITERIOSVALORES'
				lcRetorno = 'CAV'
			case lcEntidad == 'DESPACHODEIMPORTACION'
				lcRetorno = 'DDI'
			case lcEntidad == 'SELECCIONDESPACHO'
				lcRetorno = 'SDD'
			case lcEntidad == 'REGISTRODESALUDSERVIDORDEDATOS'
				lcRetorno = 'SQL'
			case lcEntidad == 'REGIMENIMPOSITIVO'
				lcRetorno = 'REG'
			case lcEntidad == 'CLASIFICACIONCONCEPTOPAGO'
				lcRetorno = 'CCP'
			case lcEntidad == 'CONCEPTOPAGO'
				lcRetorno = 'CPA'
			case lcEntidad == 'COMPROBANTEPAGO'
				lcRetorno = 'COP'
			case lcEntidad == 'COMPROBANTEDERETENCIONESIVA'
				lcRetorno = 'CRI'
			case lcEntidad == 'COMPROBANTEDERETENCIONESGANANCIAS'
				lcRetorno = 'CRG'
			case lcEntidad == 'COMPROBANTEDERETENCIONESSUSS'
				lcRetorno = 'CRS'
			case lcEntidad == 'TIPODEOPERACIONAFIP'
				lcRetorno = 'TOA'
			case lcEntidad == 'ASOCIACIONARTICULOSOPERACIONESAFIP'
				lcRetorno = 'AAO'
			case lcEntidad == 'FERIADO'
				lcRetorno = 'FER'
			case lcEntidad == 'CLASIFICACIONCONCEPTOCAJA'
				lcRetorno = 'CCC'
			case lcEntidad == 'REGISTRODEACTIVIDADDET'
				lcRetorno = 'ACD'
			case lcEntidad == 'DATOSADICIONALESCOMPROBANTESA'
				lcRetorno = 'DAA'
			case lcEntidad == 'MOTIVODATOSADICIONALESCOMPROBANTESA'
				lcRetorno = 'MDA'
			case lcEntidad == 'AGRUPAMIENTOPUBLICACIONES'
				lcRetorno = 'APP'
			case lcEntidad == 'MAILPORLOTE'
				lcRetorno = 'MFA'
			case lcEntidad == 'EMAIL'
				lcRetorno = 'MIL'
			case lcEntidad == 'CUENTACORREO'
				lcRetorno = 'SMT'
			case lcEntidad == 'CONCEPTOLIQUIDACIONTARJETA'
				lcRetorno = 'CLT'
			case lcEntidad == 'LIQUIDACIONDIARIA'
				lcRetorno = 'LDT'
			case lcEntidad == 'LIQUIDACIONMENSUAL'
				lcRetorno = 'LIQ'
			case lcEntidad == 'PLANDECUENTAS'
				lcRetorno = 'CTA'
			case lcEntidad == 'COMPROBANTEDERETENCIONRECIBIDO'
				lcRetorno = 'CRR'
			case lcEntidad == 'DATOSRETENCIONRECIBIDO'
				lcRetorno = 'DRR'
			case lcEntidad == 'REPORTEELECTRONICO'
				lcRetorno = 'RPE'
			case lcEntidad == 'CLIENTERECOMENDANTE'
				lcRetorno = 'CLR'
			case lcEntidad == 'COMPLETARDESDEVENTAS'
				lcRetorno = 'CVE'
			case lcEntidad == 'CENTRODECOSTO'
				lcRetorno = 'CCO'
			case lcEntidad == 'DISTRIBUCIONCENTRODECOSTO'
				lcRetorno = 'DCC'
			case lcEntidad == 'ASIENTO'
				lcRetorno = 'ASI'
			case lcEntidad == 'RAZONSOCIAL'
				lcRetorno = 'RAZ'
			case lcEntidad == 'EJERCICIO'
				lcRetorno = 'EJR'
			case lcEntidad == 'ASIGNARZBD'
				lcRetorno = 'ARB'
			case lcEntidad == 'IMPDIRVAL'
				lcRetorno = 'IDV'
			case lcEntidad == 'IMPDIRART'
				lcRetorno = 'IDA'
			case lcEntidad == 'IMPDIRCLI'
				lcRetorno = 'IDC'
			case lcEntidad == 'IMPDIRPRO'
				lcRetorno = 'IDP'
			case lcEntidad == 'IMPDIRIMP'
				lcRetorno = 'IDI'
			case lcEntidad == 'IMPDIRCAJ'
				lcRetorno = 'IDJ'
			case lcEntidad == 'IMPDIRCON'
				lcRetorno = 'IDO'
			case lcEntidad == 'IMPDIRDES'
				lcRetorno = 'IDD'
			case lcEntidad == 'IMPDIROPE'
				lcRetorno = 'IDT'
			case lcEntidad == 'IMPDIRLIQ'
				lcRetorno = 'IDQ'
			case lcEntidad == 'IMPVERCC'
				lcRetorno = 'IVC'
			case lcEntidad == 'CONTABILIZACION'
				lcRetorno = 'CAT'
			case lcEntidad == 'ASIENTOTIPO'
				lcRetorno = 'ATI'
			case lcEntidad == 'CIERREEJERCICIO'
				lcRetorno = 'CEJ'
			case lcEntidad == 'IMPDIRCCA'
				lcRetorno = 'IDX'
			case lcEntidad == 'IMPDIRCCC'
				lcRetorno = 'IDZ'
			case lcEntidad == 'APERTURAEJERCICIO'
				lcRetorno = 'ADE'
			case lcEntidad == 'ASIENTOSPERIODICOS'
				lcRetorno = 'RAS'
			case lcEntidad == 'ENTREGADEMERCADERIAS'
				lcRetorno = 'EMC'
			case lcEntidad == 'CLIENTEECOMMERCE'
				lcRetorno = 'CEC'
			case lcEntidad == 'COMPROBANTESECOMMERCE'
				lcRetorno = 'COE'
			case lcEntidad == 'ECOMMERCE'
				lcRetorno = 'ECO'
			case lcEntidad == 'OPERACIONECOMMERCE'
				lcRetorno = 'OEC'
			case lcEntidad == 'PUNTOSDEVENTA'
				lcRetorno = 'PVT'
			case lcEntidad == 'SERVICIOREST'
				lcRetorno = 'RST'
			case lcEntidad == 'CLAVESECRETAREST'
				lcRetorno = 'PKR'
			case lcEntidad == 'DATOSADICIONALESSIPRIB'
				lcRetorno = 'DAS'
			case lcEntidad == 'ARTICULOINCISODATOSADICIONALESSIPRIB'
				lcRetorno = 'ADA'
			case lcEntidad == 'AGRUPALISTADOSPERSONALIZADOS'
				lcRetorno = 'ALP'
			case lcEntidad == 'REPORTEAUDITORIACIERREZ'
				lcRetorno = 'ACZ'
			case lcEntidad == 'MOTIVODESCUENTOYDEVOLUCION'
				lcRetorno = 'MDD'
			case lcEntidad == 'CODIGOAUTORIZACIONDJCP'
				lcRetorno = 'DJC'
			case lcEntidad == 'ARQUEODECAJA'
				lcRetorno = 'ARQ'
			case lcEntidad == 'CODIGODESERVICIO'
				lcRetorno = 'COS'
			case lcEntidad == 'TIPODEORDEN'
				lcRetorno = 'TDO'
			case lcEntidad == 'ESTADOSDEINTERACCION'
				lcRetorno = 'EDI'
			case lcEntidad == 'INTERACCIONDEORDEN'
				lcRetorno = 'INO'
			case lcEntidad == 'ENTIDADADICIONAL1'
				lcRetorno = 'EA1'
			case lcEntidad == 'ENTIDADADICIONAL2'
				lcRetorno = 'EA2'
			case lcEntidad == 'ENTIDADADICIONAL3'
				lcRetorno = 'EA3'
			case lcEntidad == 'ORDENDESERVICIO'
				lcRetorno = 'ODS'
			case lcEntidad == 'SELECCIONORDENDESERVICIO'
				lcRetorno = 'SOS'
			case lcEntidad == 'ERRORSAP'
				lcRetorno = 'EES'
			case lcEntidad == 'INCONSISTENCIASAP'
				lcRetorno = 'INS'
			case lcEntidad == 'SELECCIONOPERACIONECOMMERCE'
				lcRetorno = 'SOP'
			case lcEntidad == 'GESTIONVENDEDOR'
				lcRetorno = 'GDV'
			case lcEntidad == 'FILTRARCOMPROBANTESACONTROLAR'
				lcRetorno = 'FCC'
			case lcEntidad == 'COTIZACION'
				lcRetorno = 'NCZ'
			case lcEntidad == 'EMAILENCOMPROBANTE'
				lcRetorno = 'EMM'
			case lcEntidad == 'SELECCIONCOMPROBANTEASOCIADO'
				lcRetorno = 'SCA'
			case lcEntidad == 'FACTURAELECTRONICADECREDITO'
				lcRetorno = 'FEM'
			case lcEntidad == 'NOTADECREDITOELECTRONICADECREDITO'
				lcRetorno = 'CEM'
			case lcEntidad == 'NOTADEDEBITOELECTRONICADECREDITO'
				lcRetorno = 'DEM'
			case lcEntidad == 'CONFIRMACIONFECHAVTOMIPYME'
				lcRetorno = 'CFV'
			case lcEntidad == 'NUEVOENTREGAONLINE'
				lcRetorno = 'NEO'
			case lcEntidad == 'SELECCIONDISENOIMPORTACION'
				lcRetorno = 'SDO'
			case lcEntidad == 'ENVIODEMENSAJERIA'
				lcRetorno = 'EME'
			case lcEntidad == 'DATOSTAREAPROGRAMADAECOMMERCE'
				lcRetorno = 'TPE'
			case lcEntidad == 'VALORESENTRANSITO'
				lcRetorno = 'VTR'
			case lcEntidad == 'CONFIRMACIONVALORESENTRANSITO'
				lcRetorno = 'VTC'
			case lcEntidad == 'DATOSTRANSACCIONBANCARIA'
				lcRetorno = 'DTB'
			case lcEntidad == 'REGISTRODECUENTA'
				lcRetorno = 'RCT'
			case lcEntidad == 'TRANSFERENCIAENTRECUENTAS'
				lcRetorno = 'TEC'
			case lcEntidad == 'COMPLETARDATOSREGISTRO'
				lcRetorno = 'DCB'
			case lcEntidad == 'CONCEPTOENTIDADFINANCIERA'
				lcRetorno = 'CEF'
			case lcEntidad == 'MOVIMIENTOBANCARIO'
				lcRetorno = 'MBC'
			case lcEntidad == 'CONCILIACIONES'
				lcRetorno = 'COB'
			case lcEntidad == 'HERRAMIENTACONCILIACION'
				lcRetorno = 'HCB'
			case lcEntidad == 'PREPARACIONDEMERCADERIA'
				lcRetorno = 'PRM'
			case lcEntidad == 'FACTURAAGRUPADA'
				lcRetorno = 'FAG'
			case lcEntidad == 'TIPODECOMPROBANTEDECOMPRA'
				lcRetorno = 'TCC'
			case lcEntidad == 'DEUDADECHEQUES'
				lcRetorno = 'DCH'
			case lcEntidad == 'CHEQUESDISPONIBLES'
				lcRetorno = 'CHD'
			case lcEntidad == 'CODBARRAALTER'
				lcRetorno = 'CAB'
			case lcEntidad == 'IMPDIRCUE'
				lcRetorno = 'IDB'
			case lcEntidad == 'NOTADECREDITOAGRUPADA'
				lcRetorno = 'NAG'
			case lcEntidad == 'NOTADEDEBITOAGRUPADA'
				lcRetorno = 'XAD'
			case lcEntidad == 'ENVIODECUENTACORRIENTEPORMAIL'
				lcRetorno = 'ECM'
			case lcEntidad == 'DATOSADICIONALESSIRE'
				lcRetorno = 'DSI'
			case lcEntidad == 'INDICESINFLACION'
				lcRetorno = 'IND'
			case lcEntidad == 'HERRAMIENTAAGRUPADORADEPACKS'
				lcRetorno = 'PCK'
			case lcEntidad == 'LINKQRENETIQUETA'
				lcRetorno = 'LQR'
			case lcEntidad == 'WEBHOOK'
				lcRetorno = 'WHK'
			case lcEntidad == 'TIQUETDECAMBIO'
				lcRetorno = 'TDC'
			case lcEntidad == 'PERSONALIZACIONDEENTIDADES'
				lcRetorno = 'PEN'
			case lcEntidad == 'IMPDIRMOT'
				lcRetorno = 'IDM'
			case lcEntidad == 'RENUMERAASIENTOS'
				lcRetorno = 'RNA'
			case lcEntidad == 'DIRECCIONENTREGAENCOMPROBANTE'
				lcRetorno = 'DIE'
			case lcEntidad == 'REGISTROLIQUIDACIONCONSIGNACIONES'
				lcRetorno = 'RLC'
			case lcEntidad == 'FECHACANCELACION'
				lcRetorno = 'FEC'
			case lcEntidad == 'MARCA'
				lcRetorno = 'MAR'
			case lcEntidad == 'ETIQUETASECOMMERCE'
				lcRetorno = 'ETE'
			case lcEntidad == 'CATEGORIASECOMMERCE'
				lcRetorno = 'CTG'
			case lcEntidad == 'CONFIGURACIONARTICULOECOMMERCE'
				lcRetorno = 'CED'
			case lcEntidad == 'CATEGORIASGOOGLESHOPPING'
				lcRetorno = 'CGS'
			case lcEntidad == 'APERTURAAUTOMATICAENTIDADES'
				lcRetorno = 'AAE'
			case lcEntidad == 'OPEECOMENPROCESO'
				lcRetorno = 'CY3'
			case lcEntidad == 'CAEA'
				lcRetorno = 'OCA'
			case lcEntidad == 'CAEAINFORMA'
				lcRetorno = 'IMC'
			case lcEntidad == 'VENDEDORENCOMPROBANTE'
				lcRetorno = 'VEC'
			case lcEntidad == 'CONDICIONDEPAGOENCOMPROBANTE'
				lcRetorno = 'ECP'
			case lcEntidad == 'INVENTARIO'
				lcRetorno = 'INV'
			case lcEntidad == 'INSUMO'
				lcRetorno = 'INP'
			case lcEntidad == 'MOTIVODESCARTE'
				lcRetorno = 'MDE'
			case lcEntidad == 'CONSUMOPRODUCCION'
				lcRetorno = 'CSM'
			case lcEntidad == 'MAQUINARIA'
				lcRetorno = 'MQP'
			case lcEntidad == 'CLASIFICACIONPRODUCCION'
				lcRetorno = 'CLP'
			case lcEntidad == 'RUBROPRODUCCION'
				lcRetorno = 'RBP'
			case lcEntidad == 'PROCESOPRODUCCION'
				lcRetorno = 'PRP'
			case lcEntidad == 'TIPIFICACIONPRODUCCION1'
				lcRetorno = 'TP1'
			case lcEntidad == 'TIPIFICACIONPRODUCCION2'
				lcRetorno = 'TP2'
			case lcEntidad == 'CURVADEPRODUCCION'
				lcRetorno = 'CVP'
			case lcEntidad == 'TALLER'
				lcRetorno = 'TLL'
			case lcEntidad == 'MODELODEPRODUCCION'
				lcRetorno = 'MDP'
			case lcEntidad == 'ORDENDEPRODUCCION'
				lcRetorno = 'OPP'
			case lcEntidad == 'GESTIONDEPRODUCCION'
				lcRetorno = 'GOP'
			case lcEntidad == 'MOVIMIENTOSTOCKAPRODUCC'
				lcRetorno = 'MSP'
			case lcEntidad == 'STOCKINVENTARIO'
				lcRetorno = '013'
			case lcEntidad == 'MOVIMIENTOSTOCKAINVENT'
				lcRetorno = 'MSI'
			case lcEntidad == 'MOVIMIENTOSTOCKDESDEPRODUCC'
				lcRetorno = 'MSD'
			case lcEntidad == 'FINALDEPRODUCCION'
				lcRetorno = 'FPR'
			case lcEntidad == 'FILTRARCOMPROBANTESAINSERTAR'
				lcRetorno = 'FCI'
			case lcEntidad == 'SELECOMPAINSERTAR'
				lcRetorno = 'SCI'
			case lcEntidad == 'INFORMEVENTASLPS'
				lcRetorno = 'IVS'
			case lcEntidad == 'SELECCHEQUETERCEROS'
				lcRetorno = 'SCT'
			case lcEntidad == 'SELECHEQUEAINSERTAR'
				lcRetorno = 'SCH'
			case lcEntidad == 'RETIRODEEFECTIVO'
				lcRetorno = 'RDE'
			case lcEntidad == 'AJUSTECHEQUERECHAZADO'
				lcRetorno = 'AJR'
			case lcEntidad == 'GESTIONCHCUSTODIA'
				lcRetorno = 'GCC'
			case lcEntidad == 'GENERADORTOKEN'
				lcRetorno = 'CPT'
			case lcEntidad == 'LISTADECOSTOSDEPRODUCCION'
				lcRetorno = 'LCP'
			case lcEntidad == 'MODIFICACIONDECOSTOSDEPRODUCCION'
				lcRetorno = 'MCP'
			case lcEntidad == 'COTIZACIONPRODUCCION'
				lcRetorno = 'CGO'
			case lcEntidad == 'LIQUIDACIONDETALLER'
				lcRetorno = 'LTP'
			case lcEntidad == 'COSTODEINSUMO'
				lcRetorno = '019'
			case lcEntidad == 'PROCESARNCPENDIENTEPROMOBANCO'
				lcRetorno = 'PCB'
			case lcEntidad == 'ALIVIODECAJA'
				lcRetorno = 'ADC'
			case lcEntidad == 'REGISTRODECOSTOS'
				lcRetorno = 'CMV'
			case lcEntidad == 'FILTRARSTOCKYPRECIOCMV'
				lcRetorno = 'FSP'
			case lcEntidad == 'ADT_VENDEDOR'
				lcRetorno = 'AUDVEN'
			case lcEntidad == 'ADT_ARTICULO'
				lcRetorno = 'AUDART'
			case lcEntidad == 'ADT_PROVEEDOR'
				lcRetorno = 'AUDPRV'
			case lcEntidad == 'ADT_CLIENTE'
				lcRetorno = 'AUDCLI'
			case lcEntidad == 'ADT_STOCKARTICULOS'
				lcRetorno = 'AUD024'
			case lcEntidad == 'ADT_PRECIODEARTICULO'
				lcRetorno = 'AUD018'
			case lcEntidad == 'ADT_STOCKCOMBINACION'
				lcRetorno = 'AUD012'
			case lcEntidad == 'ADT_CONSUMOCLIENTE'
				lcRetorno = 'AUDCCL'
			case lcEntidad == 'ADT_LIMITECONSUMO'
				lcRetorno = 'AUDLCN'
			case lcEntidad == 'ADT_DESCUENTO'
				lcRetorno = 'AUDDES'
			case lcEntidad == 'ADT_ESTADOCONTROLADORFISCAL'
				lcRetorno = 'AUD140'
			case lcEntidad == 'ADT_STOCKINVENTARIO'
				lcRetorno = 'AUD013'
		endcase

		return lcRetorno
	endfunc

enddefine